import type { Config } from "tailwindcss";

// Design tokens ported 1:1 from DESIGN.md ("Warm Editorial Atelier")
// and the approved Stitch prototype screens.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#ede7e2",
        "on-tertiary-fixed-variant": "#673b34",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "surface-container": "#f3ede7",
        "secondary-container": "#c4e8d1",
        "on-surface": "#1d1b18",
        background: "#fff8f3",
        "inverse-primary": "#ffb5a0",
        "surface-variant": "#e7e1dc",
        "surface-bright": "#fff8f3",
        "primary-fixed-dim": "#ffb5a0",
        surface: "#fff8f3",
        "surface-dim": "#dfd9d4",
        "on-primary-fixed": "#3b0900",
        "on-secondary-fixed": "#002113",
        "surface-tint": "#9b442c",
        primary: "#984229",
        "surface-container-low": "#f9f2ed",
        "on-error-container": "#93000a",
        "on-background": "#1d1b18",
        "on-tertiary-fixed": "#33110c",
        tertiary: "#7f4f48",
        "surface-container-highest": "#e7e1dc",
        "primary-container": "#b7593f",
        "tertiary-fixed-dim": "#f6b7ae",
        secondary: "#456553",
        "secondary-fixed": "#c7ebd4",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-surface-variant": "#55423d",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#dcc1ba",
        "secondary-fixed-dim": "#abcfb8",
        "on-primary-container": "#fffbff",
        "tertiary-container": "#9b675f",
        "on-secondary-fixed-variant": "#2d4d3c",
        "on-secondary-container": "#496a57",
        "tertiary-fixed": "#ffdad4",
        "inverse-on-surface": "#f6f0ea",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffdbd1",
        outline: "#88726c",
        "on-tertiary-container": "#fffbff",
        "on-primary-fixed-variant": "#7c2d17",
        "inverse-surface": "#32302d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "1.25rem",
        margin: "3.5rem",
        "space-2xl": "5rem",
        "gutter-mobile": "1rem",
        "space-lg": "1.75rem",
        "space-md": "1rem",
        "space-xl": "3rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "margin-tablet": "2rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        "headline-lg": ["var(--font-bodoni)", "serif"],
        "headline-xl": ["var(--font-bodoni)", "serif"],
        "label-md": ["var(--font-barlow)", "sans-serif"],
        "body-md": ["var(--font-garamond)", "serif"],
        "display-hero": ["var(--font-bodoni)", "serif"],
        "headline-xl-mobile": ["var(--font-bodoni)", "serif"],
        "label-lg": ["var(--font-barlow)", "sans-serif"],
        "headline-md": ["var(--font-bodoni)", "serif"],
        "headline-sm": ["var(--font-garamond)", "serif"],
        "display-hero-mobile": ["var(--font-bodoni)", "serif"],
        "body-sm": ["var(--font-garamond)", "serif"],
        "body-lg": ["var(--font-garamond)", "serif"],
        "label-sm": ["var(--font-barlow)", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["36px", { lineHeight: "44px", fontWeight: "500" }],
        "headline-xl": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.16em", fontWeight: "600" },
        ],
        "body-md": ["17px", { lineHeight: "26px", fontWeight: "400" }],
        "display-hero": [
          "64px",
          { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
        "headline-xl-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "label-lg": [
          "14px",
          { lineHeight: "18px", letterSpacing: "0.14em", fontWeight: "600" },
        ],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "headline-sm": [
          "22px",
          { lineHeight: "30px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "display-hero-mobile": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "body-sm": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "label-sm": [
          "10px",
          { lineHeight: "14px", letterSpacing: "0.18em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
